### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by wlabuschagne** [GrayAn/jira_rabbitmq_webhook#1]
Hi there. I am getting the following error when running your app.

RuntimeError: wsgi app should be either Application or async function returning Application, got <jira_rabbitmq_webhook.application.JRWApplication object at 0x7f19ebb35a60>

I am new to Python, is installed the app as per your instruction.

Please help!.

Regards
Willem

**Comment by GrayAn** [comment]
Hi Willem!

Could you post your Python version and the list of the installed packages with their versions?

**Comment by wlabuschagne** [comment]
Hi , thanks for quick reply.

root@857205022ed9:/usr/local/lib/python3.8/site-packages/jira_rabbitmq_webhook# python -V
Python 3.8.3
root@857205022ed9:/usr/local/lib/python3.8/site-packages/jira_rabbitmq_webhook# pip freeze
aioamqp==0.14.0
aiohttp==3.6.2
async-timeout==3.0.1
attrs==19.3.0
chardet==3.0.4
gunicorn==20.0.4
idna==2.9
jira-rabbitmq-webhook==0.1.0
multidict==4.7.6
pamqp==2.3.0
yarl==1.4.2

Kind Regards
Willem

**Comment by GrayAn** [comment]
It was a compatibility issue with the newer version of aiohttp (one of the dependent libraries). Fixed it and uploaded the fresh version on the pypi.

Feel free to ask any questions about application functionality. It was working with the particular Jira webhook structure and I'm afraid it may have some issues with another Jira instances.

**Comment by wlabuschagne** [comment]
Thanks a lot, you a star!!
